### ISSUE TITLE
Something wrong when I compile in Windows 10

### ISSUE THREAD

**Issue by OsbertWang** [liantze/cdcalendar#1]
Hi~

After I compile the ChineseLunarCalender.tex via lualatex in my computer, the output can be written but the figures go to the wrong position.

well~I compile the ChineseLunarCalender.tex three times, then it's OK!

**Comment by liantze** [comment]
Yep this is common when the `(current page.south)` etc anchors are used; you'll need to recompile 2-3 times for things to show up in the right positions. I'm overhauling this a bit though so that this shouldn't be necessary; the fix will also allow XeLaTeX compilation—which means compiling a Chinese calendar will be much faster. Coming soon!
